//
//  QRTypes.swift
//  AppruvQR
//
//  Created by Jessica Laurentia Tedja on 10/04/26.
//
import Foundation
import CryptoKit

struct QRCodePayload: Codable {
    let user_id: String
    let name: String
    let timestamp: TimeInterval
    let signature: String
}

struct ScannerValidator {
    static let secretKey = SymmetricKey(data: Data("OfflineAccountabilityAppSecret2026".utf8))
    static func processScan(jsonString: String, requiredReviewerID: String) -> (success: Bool, message: String, payload: QRCodePayload?) {
        
        guard let data = jsonString.data(using: .utf8),
              let payload = try? JSONDecoder().decode(QRCodePayload.self, from: data) else {
            return (false, "[ERROR] Invalid QR code or not generated by this app.", nil)
        }

        let currentTimestamp = Date().timeIntervalSince1970
        let ageInSeconds = currentTimestamp - payload.timestamp

        if ageInSeconds > 10 {
            return (false, "[ERROR] QR code expired. Ask the reviewer to refresh.", payload)
        }
        if ageInSeconds < -5 {
            return (false, "[ERROR] Time is not synchronized. Please check your device clock.", payload)
        }

        let dataToSign = "\(payload.user_id)|\(Int(payload.timestamp))"
        let expectedSignature = HMAC<SHA256>.authenticationCode(for: Data(dataToSign.utf8), using: secretKey)
        let expectedSignatureString = Data(expectedSignature).base64EncodedString()

        if payload.signature != expectedSignatureString {
            return (false, "[ERROR] Fake QR detected: cryptographic signature mismatch.", payload)
        }

        if !requiredReviewerID.isEmpty && payload.user_id != requiredReviewerID {
            return (false, "[ERROR] Wrong person: this task is for \(requiredReviewerID), but scanned by \(payload.user_id).", payload)
        }

        return (true, "Approved by \(payload.name)!", payload)
    }
}
